### ISSUE TITLE
Add dist/ to .gitignore

### ISSUE THREAD

**Issue by doggy8088** [NascHQ/share-api-polyfill#10]
I'd like to suggest to remote/ignore `dist/` folder from the repo.

**Comment by felipenmoura** [comment]
Yup, I thought on that too.
I left it there so people would be able to use the Github itself as a "CDN", loading it straight from the demo page (which also uses it)...I did that for simplicity when someone wants to try it quickly.

**Comment by doggy8088** [comment]
I think publish to npm registry might be more "offical" way to release versions.  You can use [unpkg](https://unpkg.com/) to load files, they also have CDN too. :)

**Comment by felipenmoura** [comment]
Good point.
Actually, it was such a good point, I just did it :)

https://www.npmjs.com/package/share-api-polyfill

Thanks

**Comment by doggy8088** [comment]
Great! So here is your direct link to the js file: [https://unpkg.com/share-api-polyfill@1.0.2/src/share.js](https://unpkg.com/share-api-polyfill@1.0.2/src/share.js) or [https://unpkg.com/share-api-polyfill/src/share.js](https://unpkg.com/share-api-polyfill/src/share.js) 😄

**Comment by felipenmoura** [comment]
PR merged and latest version (1.0.3) published to NPM.
Thanks a lot :)
