### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Laurensdc** [NascHQ/share-api-polyfill#29]
Trying to include this in a Vue.js project, and getting the following error:

```
ERROR in ./node_modules/share-api-polyfill/dist/share-min.js 
Module parse failed: Unexpected token (1:664) 
You may need an appropriate loader to handle this file type.
```

**Comment by LuisKrotz** [comment]
You Could try using with `window.require`.

`window.share = require('../js/vendor/NascHQ-share-api-polyfill.min');`

and then call it like:

```
            share (event) {
                let self = this;

                navigator.share({
                    title: 'Web Share API Polyfill',
                    text: 'A polyfill for the Share API. Use it to share in both desktops and mobile devices.',
                    url: self.getUrlFromElement(event),

                    fbId: '######',
                    hashtags: 'javascript, shareAPI, polyfill'
                })
                .then( _ => console.log('Yay, you shared it :)'))
                .catch( error => console.log('Oh noh! You couldn\'t share it! :\'(\n', error));
            }
```

`@click.prevent="share($event)" `

**Comment by ftonato** [comment]
Hello @Laurensdc,

You can follow the suggest presented by @LuisKrotz but u don't need import using require on `VueJS`.

I created an example, you can check here -> https://codesandbox.io/s/jpl35m4qx5?fontsize=14

**Comment by felipenmoura** [comment]
Did you get it to work, @Laurensdc ?
I'm closing it now, but if you face trouble, let's know.
