### ISSUE TITLE
BUG REPORT: telegram share not working

### ISSUE THREAD

**Issue by plinionaves** [NascHQ/share-api-polyfill#31]
Telegram sharing is not working, the scope of the constant `payload` is wrong.

![image](https://user-images.githubusercontent.com/7607265/57309524-a07aa480-70be-11e9-9ca7-bbb1d294959d.png)

#

**Comment by plinionaves** [comment]
Hello @ftonato

Thanks for the tip and help!

I made this change, please make sure it is correct now.

Hug!

**Comment by felipenmoura** [comment]
The #32 fixed it, thanks :) 👍

**Comment by plinionaves** [comment]
Hi @felipenmoura, nice!

I thank you!
