### ISSUE TITLE
Doesn't seem to work in Edge

### ISSUE THREAD

**Issue by JacobDB** [NascHQ/share-api-polyfill#34]
Getting the following error:

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number       
share-min.js (1,8218)
```

**Comment by JacobDB** [comment]
Looks like it's complaining about this specifically...

https://github.com/NascHQ/share-api-polyfill/blob/master/dist/share.js#L120

May be able to polyfill it, testing...

**Comment by JacobDB** [comment]
Doesn't look like a polyfill exists for the "spread" operator unfortunately. Any chance this could be updated without using that?

**Comment by JacobDB** [comment]
Never mind, seems to be working now. Not sure what was up previously.

**Comment by felipenmoura** [comment]
Hi @JacobDB , thanks for reporting and testing it.
We transpile the code, so that problem with spread operators should not happen, indeed!
Good thing you got it to work again :)
