### ISSUE TITLE
npm ERR! git: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by patrick-entinux** [NascHQ/share-api-polyfill#36]
When installed through NPM, I get an error about the package being a git repository. Can be reproduced by creating a new project like this: 

```
$ npm init -y                                    
Wrote to ~/share-api-test/package.json:

{
  "name": "share-api-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

$ npm install --save share-api-polyfill
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN share-api-test@1.0.0 No description
npm WARN share-api-test@1.0.0 No repository field.

+ share-api-polyfill@1.0.7
added 1 package from 1 contributor and audited 1 package in 0.792s
found 0 vulnerabilities

$ npm install                          
npm ERR! path ~/share-api-test/node_modules/share-api-polyfill
npm ERR! code EISGIT
npm ERR! git ~/share-api-test/node_modules/share-api-polyfill: Appears to be a git repo or submodule.
npm ERR! git     ~/share-api-test/node_modules/share-api-polyfill
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-08-29T04_40_57_713Z-debug.log
```

It seems a similar issue was resolved by removing the .git folder of that module: https://github.com/react-native-community/react-native-safe-area-view/issues/73

I can see that share-api-polyfill has a .git folder in the npm package too:
![Untitled-1_—_missionpick__Workspace_](https://user-images.githubusercontent.com/37786000/63910729-e2ab6580-ca62-11e9-9380-bc8e8c1a7960.png)

However, I don't know why it is there. According to the npm instructions, the git folder should be ignored automatically:

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by felipenmoura** [comment]
Great, thanks @patrick-entinux :)
I'm closing the issue, then.
