### ISSUE TITLE
Support for Polish and Danish Language

### ISSUE THREAD

**Issue by NTEurocamp** [NascHQ/share-api-polyfill#41]
I'd like to use this plugin, but need support for both the Polish and Danish languages as well as the existing ones.

I'd like to contribute these if possible?

**Comment by felipenmoura** [comment]
Hi @NTEurocamp that's awesome.
Sure, all the help is quite welcome!
Feel free to submit a Pull Request with the translations you manage to make.
I do believe these two languages would be awesome additions to the polyfill.
